on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '5 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
  
  test:
    if: success() || failure()
    needs: test_schedule
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
  test1:
    needs: test_schedule
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
  test2:
    if: success() || failure()
    needs: test_schedule
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
  notification:
    if: failure() && github.event_name == 'schedule'
    needs: [test, test1, test2]
    runs-on: ubuntu-latest
    name: Notify Teams that we need to check fail on build
    steps:
    - name: Send a Notification to Teams
      id: notify
      uses: thechetantalwar/teams-notify@v2
      with:
        teams_webhook_url: ${{ secrets.TEAM_HOOK }}
        message: "Github Action Build is failing.  ${{ github.jobs.result == 'failure' }} Please check https://github.com/microsoft/PowerApps-TestEngine/actions for more details."