on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '5 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
  notification:
    if: github.event_name == 'schedule' || github.event_name == 'push' && github.jobs.result == 'failure'
    needs: test_schedule 
    runs-on: ubuntu-latest
    name: Notify Teams that we need to check fail on build
    steps:
    - name: Send a Notification to Teams
      id: notify
      uses: thechetantalwar/teams-notify@v2
      with:
        teams_webhook_url: ${{ secrets.TEAM_HOOK }}
        message: "Github Action Build is failing. Please check https://github.com/microsoft/PowerApps-TestEngine/actions for more details."